"""Initial migration with all models and BR-03 index

Revision ID: de0411ac2671
Revises: 
Create Date: 2026-02-12 14:01:34.396014

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'de0411ac2671'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('comments',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('entity_type', sa.String(length=20), nullable=False),
    sa.Column('entity_id', sa.String(length=36), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('author', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_comments_entity_id'), 'comments', ['entity_id'], unique=False)
    op.create_index(op.f('ix_comments_entity_type'), 'comments', ['entity_type'], unique=False)
    op.create_table('projects',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('documents',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('project_id', sa.String(length=36), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('template_type', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_documents_project_id'), 'documents', ['project_id'], unique=False)
    op.create_index(op.f('ix_documents_template_type'), 'documents', ['template_type'], unique=False)
    op.create_table('epics',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('project_id', sa.String(length=36), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_epics_project_id'), 'epics', ['project_id'], unique=False)
    op.create_index(op.f('ix_epics_status'), 'epics', ['status'], unique=False)
    op.create_table('sprints',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('project_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('goal', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('start_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('end_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sprints_project_id'), 'sprints', ['project_id'], unique=False)
    op.create_index(op.f('ix_sprints_status'), 'sprints', ['status'], unique=False)
    op.create_table('stories',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('epic_id', sa.String(length=36), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('priority', sa.String(length=20), nullable=False),
    sa.Column('story_points', sa.Integer(), nullable=True),
    sa.Column('assignee', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('story_points IS NULL OR story_points IN (1, 2, 3, 5, 8, 13, 21)', name='ck_story_points_fibonacci'),
    sa.ForeignKeyConstraint(['epic_id'], ['epics.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_stories_assignee'), 'stories', ['assignee'], unique=False)
    op.create_index(op.f('ix_stories_epic_id'), 'stories', ['epic_id'], unique=False)
    op.create_index(op.f('ix_stories_priority'), 'stories', ['priority'], unique=False)
    op.create_index(op.f('ix_stories_status'), 'stories', ['status'], unique=False)
    op.create_table('story_sprint',
    sa.Column('story_id', sa.String(length=36), nullable=False),
    sa.Column('sprint_id', sa.String(length=36), nullable=False),
    sa.Column('assigned_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('sprint_status', sa.String(length=20), nullable=False),
    sa.ForeignKeyConstraint(['sprint_id'], ['sprints.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['story_id'], ['stories.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('story_id', 'sprint_id')
    )
    op.create_index(op.f('ix_story_sprint_sprint_status'), 'story_sprint', ['sprint_status'], unique=False)
    
    # BR-03: Partial unique index - a story can only be in ONE active sprint at a time
    # This enforces the business rule at the database level using denormalized sprint_status
    op.execute("""
        CREATE UNIQUE INDEX idx_story_active_sprint 
        ON story_sprint (story_id) 
        WHERE sprint_status = 'active'
    """)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # BR-03: Drop partial unique index
    op.execute("DROP INDEX IF EXISTS idx_story_active_sprint")
    
    op.drop_index(op.f('ix_story_sprint_sprint_status'), table_name='story_sprint')
    op.drop_table('story_sprint')
    op.drop_index(op.f('ix_stories_status'), table_name='stories')
    op.drop_index(op.f('ix_stories_priority'), table_name='stories')
    op.drop_index(op.f('ix_stories_epic_id'), table_name='stories')
    op.drop_index(op.f('ix_stories_assignee'), table_name='stories')
    op.drop_table('stories')
    op.drop_index(op.f('ix_sprints_status'), table_name='sprints')
    op.drop_index(op.f('ix_sprints_project_id'), table_name='sprints')
    op.drop_table('sprints')
    op.drop_index(op.f('ix_epics_status'), table_name='epics')
    op.drop_index(op.f('ix_epics_project_id'), table_name='epics')
    op.drop_table('epics')
    op.drop_index(op.f('ix_documents_template_type'), table_name='documents')
    op.drop_index(op.f('ix_documents_project_id'), table_name='documents')
    op.drop_table('documents')
    op.drop_table('projects')
    op.drop_index(op.f('ix_comments_entity_type'), table_name='comments')
    op.drop_index(op.f('ix_comments_entity_id'), table_name='comments')
    op.drop_table('comments')
    # ### end Alembic commands ###
